import { NAV_COMMANDS, NAV_COMMANDS_CONTENTS } from "./nav-commands";
import {
  COMMERCIAL_PROJECT_COMMANDS,
  MISK_PROJECT_COMMANDS,
  PERSONAL_PROJECT_COMMANDS,
  PROJECT_COMMANDS,
  PROJECT_COMMAND_CONTENTS,
} from "./project-commands";

const COMMANDS = [
  ...NAV_COMMANDS,
  ...PROJECT_COMMANDS,
  ...COMMERCIAL_PROJECT_COMMANDS,
  ...PERSONAL_PROJECT_COMMANDS,
  ...MISK_PROJECT_COMMANDS,
];

export const COMMAND_CONTENTS = {
  ...NAV_COMMANDS_CONTENTS,
  ...PROJECT_COMMAND_CONTENTS,
};
